name: SELinux fcontext Autograding

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  autograde:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout student submission
        uses: actions/checkout@v4

      - name: Make test executable
        run: chmod +x tests/test.sh

      - name: Run Autograder
        run: bash tests/test.sh student_solution.sh
